blueprint:
  name: zzz beta - Zone Entering Notification
  description: Send a notification to a device when a person enters a specific zone.
  domain: automation

  input:
    person_entity:
      name: Person
      selector:
        entity:
          domain: person
          multiple: true
    zone_entity:
      name: Zone
      selector:
        entity:
          domain: zone
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        #target:
          device:
            integration: mobile_app

trigger:
  platform: state
  entity_id: !input person_entity
  to: !input zone_entity

variables:
  zone_entity: !input zone_entity
  # This is the state of the person when it's in this zone.
  zone_state: "{{ states[zone_entity].name }}"
  person_entity: !input person_entity
  person_name: "{{ states[person_entity].name }}"

condition:
  condition: template
  #value_template: "{{ trigger.from_state.state != 'zone_state' and trigger.to_state.state == 'zone_state' }}"
  value_template: >-
    {{ trigger.from_state.state != "home" and trigger.to_state.state == "home" }}

action:
  domain: mobile_app
  type: notify
  device_id: !input notify_device
  message: "{{ person_name }} has entered {{ zone_state }}"
  data:
    confirmation: true
    ttl: 1
    priority: high